name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rpi-kernel-builder

    - run: |
        cd ./workspace/
        git clone --depth=1 --branch rpi-6.18.y https://github.com/raspberrypi/linux.git

    - name: build
      run: |
        docker run --rm \
          -v "$PWD/workspace/:/workspace/"\
          rpi-kernel-builder /workspace/build.sh
