name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rpi-kernel-builder


    - run: git clone --depth=1 --branch rpi-6.18.y https://github.com/raspberrypi/linux.git

    - name: build
      run: |
        docker run --rm \
          -v "$PWD/linux/:/workspace/linux/" \
          -v "$PWD/config/:/workspace/config/"\
          -v "$PWD/output/:/workspace/output/"\
          rpi-kernel-builder ./build.sh
